name = "edge-graphql"
main = "src/index.ts"
compatibility_date = "2022-09-23"
kv_namespaces = [
    { binding = "EXAMPLE_KV_LOCAL", id = "ff08d3b7ee764e64a1f37196d31a3267", preview_id = "ff08d3b7ee764e64a1f37196d31a3267" }
]
compatibility_flags = ["streams_enable_constructors"]
